export type BsPages = 'ADDRESS_SELECTOR' | 'SET_LOCATION_ON_MAP' | 'SERVICE_ESTIMATIONS' | 'CONFIRM_PICKUP' | 'NO_PAYMENT';

interface BsPageObject {
    [key: string]: BsPages
}

export const BS_PAGES: BsPageObject = {
    ADDRESS_SELECTOR: 'ADDRESS_SELECTOR',
    SET_LOCATION_ON_MAP: 'SET_LOCATION_ON_MAP',
    CONFIRM_PICKUP: 'CONFIRM_PICKUP',
    NO_PAYMENT: 'NO_PAYMENT',
    SERVICE_ESTIMATIONS: 'SERVICE_ESTIMATIONS'
}