# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# $RNFirebaseAsStaticFramework = true

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Locomotion' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'


  target 'LocomotionTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # use_frameworks!

  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseCrashlytics', :modular_headers => true
  pod 'FirebaseSessions', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
        # Ensure no pod drops below the app's minimum deployment target
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
      target.build_configurations.each do |config|
        cxx = config.build_settings['CLANG_CXX_LANGUAGE_STANDARD']
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17' unless %w[c++17 gnu++17 c++20 gnu++20].include?(cxx)
      end
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end

    if ENV['CI'] || ENV['BITRISE_BUILD_NUMBER'] || ENV['GITHUB_ACTIONS']
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          existing_cflags = config.build_settings['OTHER_CFLAGS']
          cflags = existing_cflags.nil? || existing_cflags.to_s.empty? ? '$(inherited)' : existing_cflags
          unless cflags.to_s.include?('-Wno-incompatible-pointer-types')
            extra = '-Wno-incompatible-pointer-types'
            config.build_settings['OTHER_CFLAGS'] = cflags.is_a?(Array) ? (cflags + [extra]) : "#{cflags} #{extra}"
          end

          config.build_settings['SWIFT_VERSION'] = '5'

          config.build_settings['TOOLCHAINS'] = 'com.apple.dt.toolchain.XcodeDefault'
          existing_ldflags = config.build_settings['OTHER_LDFLAGS']
          ldflags = existing_ldflags.nil? || existing_ldflags.to_s.empty? ? '$(inherited)' : existing_ldflags
          unless ldflags.to_s.include?('DT_TOOLCHAIN_DIR')
            extra = '-L$(DT_TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)'
            config.build_settings['OTHER_LDFLAGS'] = ldflags.is_a?(Array) ? (ldflags + [extra]) : "#{ldflags} #{extra}"
          end
        end
      end
    end
  end
end
