export default {
  SERVICE_ESTIMATIONS_INTERVAL_IN_SECONDS: 'riderApp.preRide.estimationsInterval',
  POST_RIDE_TIP_SETTINGS: 'riderApp.postRide.showTipPresetsAsPercentageThreshold',
  CARD_PAGE_SETTINGS: 'riderApp.onboarding.cardPageSettings',
  ENFORCE_PROFILE_PICTURE: 'riderApp.enforceProfilePicture',
  MIN_APP_VERSION: 'riderApp.minAppVersion',
  CONTACT_US_URL: 'riderApp.contactUsUrl',
  CONTACT_US_TEXT: 'riderApp.contactUsText',
  TERMS_OF_USE_URL: 'riderApp.termsOfUseUrl',
  PRIVACY_POLICY_URL: 'riderApp.privacyPolicyUrl',
  CONTACT_EMAIL: 'riderApp.contactEmail',
  CONTACT_PHONE: 'riderApp.contactPhone',
  FUTURE_RIDES_ENABLED: 'riderApp.futureRidesEnabled',
  MIN_MINUTES_BEFORE_FUTURE_RIDE: 'riderApp.minMinutesBeforeFutureRide',
  SHOW_POST_RIDE_FEEDBACK: 'riderApp.showPostRideFeedback',
  VEHICLE_COLOR: 'riderApp.vehicleIconColor',
  MEASURE_SYSTEM: 'riderApp.measureSystem',
  MULTI_SP: 'riderApp.showMultiStopPoint',
  DISABLE_CAPTCHA_UI: 'riderApp.disableCaptchaUi',
  DISABLE_CAPTCHA: 'riderApp.disableCaptcha',
  MAX_DAYS_FOR_FUTURE_RIDE: 'riderApp.daysForFutureRideBooking',
  OFFLINE_PAYMENT_TEXT: 'riderApp.offlinePaymentText',
  HIDE_PRICE: 'riderApp.hidePrice',
};
