export default {
  SERVICE_ESTIMATIONS_INTERVAL_IN_SECONDS: 'riderApp.preRide.estimationsInterval',
  CASH_ENABLED: 'payment.enableCash',
  POST_RIDE_TIP_SETTINGS: 'riderApp.postRide.showTipPresetsAsPercentageThreshold',
  CARD_PAGE_SETTINGS: 'riderApp.onboarding.cardPageSettings',
  MIN_APP_VERSION: 'riderApp.minAppVersion',
  CONTACT_US_URL: 'riderApp.contactUsUrl',
  TERMS_OF_USE_URL: 'riderApp.termsOfUseUrl',
  PRIVACY_POLICY_URL: 'riderApp.privacyPolicyUrl',
  CONTACT_EMAIL: 'riderApp.contactEmail',
  CONTACT_PHONE: 'riderApp.contactPhone',
  FUTURE_RIDES_ENABLED: 'riderApp.futureRidesEnabled',
  CASH_ENABLED_IN_APP: 'payment.enableCashInApp',
  MIN_MINUTES_BEFORE_FUTURE_RIDE: 'riderApp.minMinutesBeforeFutureRide',
  SHOW_POST_RIDE_FEEDBACK: 'riderApp.showPostRideFeedback',
};
