source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby File.read(File.join(__dir__, ".ruby-version")).strip

# Cocoapods > 1.15 required for RN 0.76
gem 'cocoapods', '>= 1.15', '< 1.17'
gem 'activesupport', '>= 6.1.7.5', '< 7.1.0'
