source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby File.read(File.join(__dir__, ".ruby-version")).strip

gem 'activesupport', '= 7.0.8'
gem 'cocoapods', '= 1.14.2'
