FROM autofleet/locomotion:2.0.6

WORKDIR /usr/src/app

# Uncomment if you want to replace assets

#COPY assets/ ./web-ui/src/assets/
#RUN rm -rf ./web-ui/build
#RUN SKIP_PREFLIGHT_CHECK=true npm run build --prefix ./web-ui/
