FROM autofleet/locomotion:2.0.8

WORKDIR /usr/src/app

# Uncomment if you want to replace assets

#COPY assets/ ./web-ui/src/assets/
#RUN rm -rf ./web-ui/build
#RUN SKIP_PREFLIGHT_CHECK=true npm run build --prefix ./web-ui/

# Uncomment if you want to replace i18n translation files
#COPY i18n/ ./i18n/