# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :generate do
  Fastlane::LaneManager.cruise_lane("ios", "icons")
  Fastlane::LaneManager.cruise_lane("android", "icons")
end

platform :ios do
  desc "Generate new icons assets"
  lane :icons do
    appicon(
      appicon_devices: [:iphone, :ios_marketing],
      appicon_path: "./ios/Locomotion/Images.xcassets/",
      appicon_image_file: './fastlane/assets/app-icon.png'
    )
  end

  desc "Change app display name"
  lane :app-name do 
    update_info_plist(
      
    )
  end


end

platform :android do
  desc "Generate new icons assets"
  lane :icons do
    android_appicon(
      appicon_image_file: './fastlane/assets/app-icon.png',
      appicon_icon_types: [:launcher],
      appicon_path: './android/app/src/main/res/mipmap'
    )
  end

end
