
export const APP_ROUTES = {
  MAIN_APP: 'MainApp',
  AUTH_LOADING: 'AuthLoading',
};

export const MAIN_ROUTES = {
  HOME: 'Home',
  RIDE_HISTORY: 'RideHistory',
  PAYMENT: 'Payment',
  ACCOUNT: 'Account',
  COMPLETED_RIDE_OVERVIEW_PAGE: 'CompletedRideOverviewPage',
  CONTACT_US: 'ContactUs',
  LOGOUT: 'Logout',
  WEBVIEW: 'webview',
  START: 'Start',
  PHONE: 'Phone',
  LOGIN: 'login',
  CODE: 'Code',
  EMAIL_CODE: 'EmailCode',
  NAME: 'Name',
  ADD_CARD: 'AddCard',
  CARD: 'AddCard',
  AVATAR: 'Avatar',
  EMAIL: 'Email',
  WELCOME: 'Welcome',
  LOCK: 'Lock',
  POST_RIDE: 'PostRide',
  CARD_DETAILS: 'CardDetails',
  EDIT_NICKNAME: 'EditNickname',
  FUTURE_RIDES: 'FutureRides',
  RIDE_PRICE_BREAKDOWN: 'RidePriceBreakdown',
  PROMO_CODE: 'PromoCode',
  MESSAGES: 'messages',
  MESSAGE_VIEW: 'messageView',
  DEV_SETTINGS_PAGE: 'DevSettingPage',
};
