name: App Test

on:
  push:
    paths:
    - 'locomotion-sdk/**'
    - '.github/workflows/sdk.yml'

defaults:
  run:
    working-directory: locomotion-sdk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          always-auth: true
          registry-url: https://registry.npmjs.org
          
      - name: Install NPM dependencies
        run: npm install -D

      - run: npm run linter
