name: autofleet server build and deploy

on:
  push:
    paths:
      # re-deploy if a change has been made to either the server or to the example
      - 'server/**'
      - 'examples/server/**'
      - '.github/workflows/build_public_server_deploy_cloud_run.yml'

jobs:
  Build_Public_GCR:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Extract branch name
        id: checkBranch
        run: echo "##[set-output name=branchCheck;]$(echo ${GITHUB_REF#refs/heads/})"
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(git rev-parse --short "$GITHUB_SHA")"

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0
        with:
            username: _json_key
            password: ${{ secrets.AF_GCR_DOCKER_PASSWORD }}
            registry: gcr.io
            repository: af-gcr/locomotion-server
            tags: ${{ steps.checkBranch.outputs.branchCheck }}-latest,${{ steps.checkBranch.outputs.branchCheck }}-${{ steps.date.outputs.date }}
            path: 'server'

  Build_Autofleet_Server:
    if: github.ref == 'refs/heads/master'
    needs: Build_Public_GCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Extract branch name
        id: checkBranch
        run: echo "##[set-output name=branchCheck;]$(echo ${GITHUB_REF#refs/heads/})"
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(git rev-parse --short "$GITHUB_SHA")"

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0
        with:
            username: _json_key
            password: ${{ secrets.LOCOMOTION_DOCKER }}
            registry: gcr.io
            repository: ${{secrets.LOCOMOTION_REPO}}
            tags: ${{ steps.checkBranch.outputs.branchCheck }}-latest,${{ steps.checkBranch.outputs.branchCheck }}-${{ steps.date.outputs.date }}
            path: 'examples/server'

  Deploy_Cloud_Run:
    if: github.ref == 'refs/heads/master'
    needs: Build_Autofleet_Server
    runs-on: ubuntu-latest
    steps:

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.LOCOMOTION_DOCKER }}

      - name: get image name
        id: getImageName
        run: |
         branchName=${GITHUB_REF#refs/heads/}
         echo $branchName
         echo "::set-output name=imageName::$(echo "gcr.io/${{secrets.LOCOMOTION_REPO}}:$branchName-latest")"
        
      - uses: google-github-actions/deploy-cloudrun@v0.9.0
        with:
          service: 'locomotion-v2'
          image: ${{ steps.getImageName.outputs.imageName }}
          region: ${{secrets.LOCOMOTION_REGION}}
