name: Internal Server Build

on:
  push:
    paths:
      - 'examples/server/**'
      - '.github/workflows/internal_server_build.yml'
# defaults:
#  run:
#   working-directory: server

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Extract branch name
        id: checkBranch
        run: echo "##[set-output name=branchCheck;]$(echo ${GITHUB_REF#refs/heads/})"
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(git rev-parse --short "$GITHUB_SHA")"

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.LOCOMOTION_DOCKER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          username: _json_key
          password: ${{ secrets.LOCOMOTION_DOCKER }}
          registry: gcr.io
          file: examples/server/Dockerfile
          repository: locomotion-v2/locomotion-server
          tags: ${{ steps.checkBranch.outputs.branchCheck }}-latest,${{ steps.checkBranch.outputs.branchCheck }}-${{ steps.date.outputs.date }}
