name: Internal Server Build

on:
  push:
    paths:
      - 'examples/server/**'
      - '.github/workflows/internal_server_build.yml'
# defaults:
#  run:
#   working-directory: server

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Extract branch name
        id: checkBranch
        run: echo "##[set-output name=branchCheck;]$(echo ${GITHUB_REF#refs/heads/})"
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(git rev-parse --short "$GITHUB_SHA")"

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0
        with:
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: gcr.io
          file: examples/server/Dockerfile
          build_args: NPM_TOKEN=${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          repository: autofleetprod/locomotion-server
          tags: ${{ steps.checkBranch.outputs.branchCheck }}-latest,${{ steps.checkBranch.outputs.branchCheck }}-${{ steps.date.outputs.date }}
