name: build public server image and push to gcr

on:
  push:
    paths:
      # build and push to gcr if a change has been made to the server
      - 'server/**'
      - '.github/workflows/push_to_docker_hub.yml'
jobs:
    Build:
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Extract branch name
        id: checkBranch
        run: echo "##[set-output name=branchCheck;]$(echo ${GITHUB_REF#refs/heads/})"
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(git rev-parse --short "$GITHUB_SHA")"

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0
        with:
            username: _json_key
            password: ${{ secrets.AF_GCR_DOCKER_PASSWORD }}
            registry: gcr.io
            repository: af-gcr/locomotion-server
            tags: ${{ steps.checkBranch.outputs.branchCheck }}-latest,${{ steps.checkBranch.outputs.branchCheck }}-${{ steps.date.outputs.date }}
            path: 'server'
