name: build and push to dockerhub

on:
  push:
    paths:
      # build and push to docker hub if a change has been made to the server
      - 'server/**'
      - '.github/workflows/push_to_docker_hub.yml'
jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.LOCOMOTION_DOCKERHUB_USERNAME}}
          password: ${{ secrets.LOCOMOTION_DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: autofleet/locomotion
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          context: server
          push: true
          tags: test_build
          labels: ${{ steps.meta.outputs.labels }}