name: App Test

on:
  push:
    paths:
    - 'locomotion-sdk/**'
    - '.github/workflows/sdk.yml'

defaults:
  run:
    working-directory: locomotion-sdk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          always-auth: true
          registry-url: https://registry.npmjs.org
          scope: '@autofleet'
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install NPM dependencies
        run: npm install -D
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm run linter
