# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Locomotion SDK Package

on:
  push:
    paths:
    - 'locomotion-sdk/**'
    - '.github/workflows/sdk.yml'

defaults:
  run:
    working-directory: locomotion-sdk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          always-auth: true
          registry-url: https://registry.npmjs.org
          scope: '@autofleet'
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install NPM dependencies
        run: npm install -D
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm run linter

      - run: npm run ts

#      - name: coverage
#        run: npm run coverage
#        env:
#          DB_PASSWORD: postgres
#          DB_USERNAME: postgres
#          DB_NAME: postgres
#          DB_HOST: 127.0.0.1
#          REDIS_HOST: localhost
#          REDIS_PORT: 6379
#
#      - run: rm -rf ./coverage


  publish-npm:
    needs: lint
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
